[package]
name = "ai-planner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "aip"
path = "src/main.rs"

[dependencies]
ai-planner-core = { path = "../ai-planner-core" }
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3"
